# Generated by Django 4.1.1 on 2022-09-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ideas',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
