# Generated by Django 4.1.1 on 2022-09-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='avg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
