# Generated by Django 4.1.1 on 2022-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='avg',
            name='avg_rating',
            field=models.TextField(blank=True, max_length=2000, verbose_name=4),
        ),
    ]
