# Generated by Django 4.1.1 on 2022-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_avg_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avg',
            name='avg_rating',
            field=models.IntegerField(blank=True, verbose_name=1),
        ),
    ]
