# Generated by Django 4.1.1 on 2022-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_avg_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='avg',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name=4),
        ),
    ]
