# Generated by Django 4.1.1 on 2022-10-03 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0009_avg_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avg',
            name='amount',
        ),
        migrations.AlterField(
            model_name='avg',
            name='avg_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
