# Generated by Django 4.1.1 on 2022-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_delete_avg'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('author', 'topic'), name='antti'),
        ),
    ]
