# Generated by Django 4.1.1 on 2022-10-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_feedback_antti'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='antti',
        ),
    ]
