# Generated by Django 4.1.1 on 2022-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
