# Generated by Django 4.1.1 on 2022-09-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
