# Generated by Django 4.1.1 on 2022-09-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_delete_feedback_delete_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=160),
        ),
    ]
